-- 清空表
DROP TABLE "db_user";
DROP TABLE "db_dept";


CREATE TABLE "DB_DEPT"
(	"ID" NUMBER,
"DEPT_NAME" VARCHAR2(20) NOT NULL ENABLE,
 CONSTRAINT "SYS_C0022671" PRIMARY KEY ("ID")
)


CREATE TABLE "DB_USER"
(	"ID" NUMBER,
"USER_NAME" VARCHAR2(50) NOT NULL ENABLE,
"AGE" NUMBER,
"STATUS" NUMBER,
"CREATE_AT" TIMESTAMP (6),
"DEPT_ID" NUMBER,
 CONSTRAINT "SYS_C0022673" PRIMARY KEY ("ID"),
 CONSTRAINT "pk_user_dept" FOREIGN KEY ("DEPT_ID")
  REFERENCES "HR"."DB_DEPT" ("ID") ON DELETE SET NULL ENABLE
)