# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:sql/mysql.sql
#    data: classpath:sql/mysql.sql
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8&useAffectedRows=true&noAccessToProcedureBodies=true
    username: root
    password: 123