# DataSource Config
spring:
  datasource:
#    schema: classpath:sql/mysql.sql
#    data: classpath:sql/mysql.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useAffectedRows=true&noAccessToProcedureBodies=true
    username: root
    password: 123456
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: hr
#    password: 123456



mybatis-plus:
  type-enums-package: pwd.allen.enums #配置枚举 支持通配符 * 或者 ; 分割
  mapper-locations:
    - classpath*:/mapper/**/*.xml #默认是这个位置
#  configuration-properties:
#    myGlobal: pwd #设置全局属性方式一
  configuration: #设置mybatis属性
    variables:
      myGlobal: pwd  ##设置全局属性方式二

logging:
  level:
    pwd.allen.mapper: debug